name: EldoriaBase
description: $description
version: '${version}'

main: me.chaos.eldoriaBase.Main
paperPluginLoader: me.chaos.eldoriaBase.MainLoader
api-version: '26.2'
load: POSTWORLD

authors: [ Chaos ]

depend:
  - "Multiverse-Core"

commands:
  warp:
    description: "Manage player warps (usage: /warp <to|set|addPublic> <id>)"
    usage: /warp <to|set|addPublic> <id>

  bank:
    description: Bank commands
    usage: /bank

  quests:
    description: Quest Menü öffnen
    usage: /quest


